services:
  default:
    build:
      context: .
      dockerfile: Dockerfile
    image: gripper-comms
    container_name: docker-gripper-comms
    stdin_open: true
    tty: true
    network_mode: host
    restart: always
    command: python3 src/gripper.py
    volumes:
      - ../src:/home/ubuntu/src:rw
      - ../config:/home/ubuntu/config:rw
  default-windows:
    extends: default
    build: 
      context: .
      dockerfile: Dockerfile.windows
